### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#1]
The old site referenced https://creativecommons.org/licenses/by/4.0/legalcode on the homepage, but had BSD checked in as LICENSE. Confirm that cc-by is correct.

**Comment by mstreit** [comment]
AFAIK we agreed to use New/Modified BSD in all our projects. @sgratzl, @ngehlenborg, @alexsb please correct me if I am wrong.

**Comment by mccalluc** [comment]
(To clarify the CC-BY was just for the documentation.)

**Comment by mstreit** [comment]
OK, then CC is correct.

**Comment by mstreit** [comment]
But it might be good to use the same license consistently (documentation + code). Opinions?

**Comment by ngehlenborg** [comment]
I vote for BSD or MIT for code, CC-BY for docs is fine.

**Comment by mstreit** [comment]
Ok, then let's keep New/Modified BSD for code and CC-BY for docs.
