### ISSUE TITLE
set up a CNAME, or not

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#2]
I had thought @ngehlenborg had registered a domain, but might be imagining that. I'm comfortable with phovea.github.io or with a domain we own, but we should clarify this before linking from caleydo.org.

**Comment by sgratzl** [comment]
what about phovea.caleydo.org?

**Comment by mstreit** [comment]
@ngehlenborg just created the github organization. 

Should I create a forward from http://phovea.caleydo.org to http://phovea.github.io?

**Comment by ngehlenborg** [comment]
I second phovea.caleydo.org

**Comment by mstreit** [comment]
Forward from http://phovea.caleydo.org to http://phovea.github.io will work soon.

**Comment by ngehlenborg** [comment]
Do you need a forward? I thought just setting the CNAME and following the instructions for GitHub pages is sufficient. Or maybe that is what you are doing ...

**Comment by mccalluc** [comment]
Ok: It already looks like a forward is in place...

```
$ curl -I http://phovea.caleydo.org
HTTP/1.1 303 See Other
..
Location: http://phovea.github.io
```

I would have slight preference for the CNAME approach, only because it would mean that the urls folks would be likely to save would really be under our control. Not something I feel strongly about.

**Comment by mstreit** [comment]
I've created a CNAME entry that points to phovea.github.io. The DNS entry is not working yet because DNS servers need time to update. I don't know why it takes so long for domains that are managed via Hover. Anyhow, should work soon.

**Comment by mstreit** [comment]
Works.
