### ISSUE TITLE
Directory structure information needs clarification

### ISSUE THREAD

**Issue by ngehlenborg** [phovea/phovea.github.io#25]
Looking at http://phovea.caleydo.org/developers/directory_structure/ I see potential for improvement: 

  1. Could we organize this into directories at the developer needs to touch vs. those that will be managed automagically by Phovea.
  1. Could we give some hint as to where the developers are supposed to add their own code and then maybe link to the corresponding coding tutorial describing how to get started with Phovea development?

**Comment by thinkh** [comment]
The link is dead. Does anyone know where the page was moved to? Is this still an issue?

**Comment by thinkh** [comment]
The page was removed when switching to phovea and with the new Docker setup it's not relevant anymore.
