### ISSUE TITLE
prerequisite knowledge for contributors

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#29]

**Comment by sgratzl** [comment]
programming languages: 
- client
  - TypeScript 2
  - SASS
- server
  - python

frameworks/libraries: 
- yeoman
- client
  - d3
  - font-awesome 
  - bootstrap
  - testing: jasmine
  - now and then: lineup.js, papaparse, select2, jquery, moment, lodash, ...
- server
  - flask
  - testing: pytest
  - now and then: numpy, pandas, requests, celery, ldap, ...

data stores: 
- redis
- mongodb
- hdf
- SQLAlchemy -> Postgres, SQlite, MySQL 
- Neo4j

build tools: 
- webpack 2
- karma test runner
- pytest runner
- python setuptools
- travis

**Comment by mstreit** [comment]
Let's update this list and add it to the website. It's a nice pointer for students and other people who join the team and want to know with which libraries and technologies they should familiarize.
