### ISSUE TITLE
Bug filing policy and template and script?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#30]
- [ ] Short writeup on what makes a good bug report
- [ ] add a template to the generator and to projects that already exist
- [ ] see if there's any easy way to get the same set of labels across a set of projects

**Comment by sgratzl** [comment]
@mccalluc I created a project to organize those things that are not related to a specific repository: https://github.com/orgs/phovea/projects/2

**Comment by mccalluc** [comment]
- Issue templates dropped into all projects, and I think that also covers how-to-write-a-good-report.
- Do have a script for applying labels to all projects, and have run it on phovea/*.
