### ISSUE TITLE
CLUE tutorial

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#38]
Earlier discussion on https://github.com/Caleydo/caleydo.github.io/issues/111

hello world at http://bl.ocks.org/sgratzl/f5e23207a83cc6f159184a85765db476

**Comment by mstreit** [comment]
Btw: @sgratzl also created a CLUE hello world that adds the authoring and presentation (storytelling) interface
https://github.com/sgratzl/clue_hello_world

![image](https://cloud.githubusercontent.com/assets/4129755/20799179/ab8c07a8-b7e1-11e6-85f1-037561c10c9c.png)

**Comment by mstreit** [comment]
A CLUE tutorial on the website could explain the following:
- how to feed the provenance graph from a very simple UI (hello world text field example shown above or simple  D3 blocks example - or both) 
- how to use it for reverting actions (like adding a back button)
- how to add the CLUE interface (exploration, authoring, presentation mode) to make use of the vistory mechanism in a self-contained standalone application 

@mccalluc, what do you think?
