### ISSUE TITLE
Try turning off GET /api/idtype

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#39]
@thinkh wrote: (https://github.com/Caleydo/caleydo.github.io/issues/132)

>I haven't debugged it, but assume that the call is triggered in [idtype.fillUp()](https://github.com/Caleydo/caleydo_core/blob/master/idtype.ts#L1002) when using [idtype.list()](https://github.com/Caleydo/caleydo_core/blob/master/idtype.ts#L1031). 
>
>A possible to prevent the call is to set the library into the [offline mode](https://github.com/Caleydo/caleydo_core/blob/master/main.ts#L33). However, I don't know the side effects in the Caleydo library.

**Comment by thinkh** [comment]
Will be solved by adding `<script src="./app.js" data-phovea-offline="true"></script>` to the index.html of the app (see  https://github.com/phovea/generator-phovea/pull/52/files#diff-ad83f1c0882be42b273a73cf33e519b5R31). This will reject all API calls or return an empty default value in the core. The new index.html is also created after merging PR https://github.com/phovea/generator-phovea/pull/52 in generator-phovea.

**Comment by sgratzl** [comment]
in the latest develop branch there is a differentiation between `idtype.list()` (just the locally known ones) and `idtype.listAll()` (all server known ones, too)
