### ISSUE TITLE
Should project list be ported? (I think not.)

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#4]
I'm not sure that the project list makes sense for us now.

Instead, I propose that the we have a naming convention for repos which makes clear what kind of thing each is, and that we only bring into the Phovea space projects which are really ready to go. Also, my sense is that applications built with Phovea will not be under github.com/phovea: They will stay under Caleydo, or in individual contributor's spaces. Taken together, this means the space will be much tider, and we won't need to maintain an outside list.

If this sounds good to folks, after we make this live, I will delete the list-generating script over at github.com/caleydo.

**Comment by ngehlenborg** [comment]
Agree on the repo naming.

Also agree that apps built with Phovea will be elsewhere and not in the Phovea organization (minus some demo apps maybe).

**Comment by mstreit** [comment]
Also agree on repo naming.

Application repos, such as pathfinder, stratomex, etc. should remain in the Caleydo github organization.

**Comment by mccalluc** [comment]
Nothing to do here:
- New phovea org on github is smaller, and we'll try to keep the names good.
- https://github.com/Caleydo/caleydo.github.io/pull/186 got rid of all the old machinery for listing the repos.
