### ISSUE TITLE
Port web_bundle_2?

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#5]
@bikramkawan: I haven't ported over your web_bundle_2: 
- I'm not sure if it's ready to go yet?
- With the work Sam has done, it might no longer be the preferred approach.
- Maybe crop the screenshots more tightly do we don't see as much of the headers which are likely to change?
- For data structures, consider capturing test, rather than copy and paste.

(Once images are checked in, they are part of the history forever, so I wanted to hold off on these until we were more confident.)

There are also a few punctuation / grammar issues I might touch, which is part of a larger discussion: How good does the writing need to be?

**Comment by mstreit** [comment]
We should not port over web_bundle_2 because it describes the old process. This will be fixed as part of #6.

Punctuation/grammar should be correct. If native speakers find issues, it would be great if the fix it right away.
