### ISSUE TITLE
Use jekyll collections instead of docu_nav

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea.github.io#9]
The current system requires us to keep a configuration file in sync with the files on disk. Instead, let's divide `_documentation` into a number of [collections](http://jekyllrb.com/docs/collections/), and then if you add a file in the right place it will just show up. Nested collections don't seem to be possible, but having to enumerate the half dozen types of collections isn't the worst thing.

**Comment by ngehlenborg** [comment]
Sounds like a good plan.

**Comment by mstreit** [comment]
Ack.

**Comment by mccalluc** [comment]
Ended up using plain directories instead of collections: I think the liquid code is more complicated than it would be for collections, but maintenance is easier, I think.
